### ISSUE TITLE
Youtube links by maka don't work

### ISSUE THREAD

**Issue by DaBomberNTG** [Pryaxis/cardinal#23]
![image](https://cloud.githubusercontent.com/assets/5866651/19760341/f416055c-9bf6-11e6-836e-5f4733d98b00.png)

![image](https://cloud.githubusercontent.com/assets/5866651/19760329/e30e686c-9bf6-11e6-8307-123f06177819.png)

As far as I've seen, this happens with 100% of the time.

**Comment by DaBomberNTG** [comment]
urban dictionary doesn't work either
![image](https://cloud.githubusercontent.com/assets/5866651/19760674/602efacc-9bf8-11e6-9827-0719f47652e9.png)

![image](https://cloud.githubusercontent.com/assets/5866651/19760645/409664de-9bf8-11e6-9dd1-3de4623642c9.png)

**Comment by nicatronTg** [comment]
Issue is URL encoding on the stringss
